name: mget
version: 0.1.0
summary: wget like tool
description: |
    wget like tool written in golang

grade: devel
confinement: devmode

parts:
    mget:
        source: .
        plugin: go
        go-importpath: github.com/weaming/mget

apps:
    mget:
        command: mget
